<div class="alert alert-block alert-success">
    <h1 align="center"> Support Vector Machine (Regression) - (Positin Salaries Dataset) </h1>
    <h3 align="center"><a href="https://github.com/amirhosein-ziaei">Amirhosein Ziaei</a></h3>
</div>

## What is SVR?

Support Vector regression is a type of Support vector machine that supports linear and non-linear regression. As it seems in the below graph, the mission is to fit as many instances as possible between the lines while limiting the margin violations. The violation concept in this example represents as ε (epsilon).

## *Implement SVR on Generated Data*

### *Importing Libraries*

In [5]:
import numpy as np
from sklearn.svm import SVR
import pylab as pl

### *Generate Data*

In [6]:
X = np.sort(5 * np.random.rand(40, 1), axis=0)
y = np.sin(X).ravel()

In [7]:
X

array([[0.11211747],
       [0.34490133],
       [0.37971321],
       [0.52497702],
       [0.64027011],
       [0.73842506],
       [0.80577084],
       [0.95066365],
       [0.96594602],
       [1.01028697],
       [1.56917524],
       [1.57114357],
       [1.75618896],
       [1.78936097],
       [1.88270919],
       [2.07216729],
       [2.09744143],
       [2.12118251],
       [2.40239845],
       [2.61575099],
       [2.9033491 ],
       [2.97606282],
       [3.10215452],
       [3.16046576],
       [3.16275681],
       [3.61142905],
       [3.75035804],
       [3.79835776],
       [4.01793537],
       [4.05598137],
       [4.14976654],
       [4.26711885],
       [4.30071922],
       [4.34418985],
       [4.34596964],
       [4.43287467],
       [4.47698498],
       [4.48341604],
       [4.54905936],
       [4.7387949 ]])

In [8]:
y

array([ 0.11188272,  0.33810382,  0.37065412,  0.50119312,  0.59741207,
        0.67312403,  0.72136471,  0.81380136,  0.82258723,  0.84698444,
        0.99999869,  0.99999994,  0.98286395,  0.97620968,  0.95174829,
        0.87692446,  0.86449823,  0.85232261,  0.67369264,  0.50194113,
        0.23599616,  0.16477495,  0.03942791, -0.01887199, -0.02116257,
       -0.45274041, -0.57185507, -0.61055811, -0.76840349, -0.79218968,
       -0.84585919, -0.90249435, -0.91645396, -0.93297706, -0.93361619,
       -0.96118955, -0.97242019, -0.97390003, -0.98669134, -0.99965138])

### *Adding Noise to Data*

In [9]:
y[::5] += 3 * (0.5 - np.random.rand(8))

In [10]:
y

array([ 1.26262632,  0.33810382,  0.37065412,  0.50119312,  0.59741207,
        1.95035613,  0.72136471,  0.81380136,  0.82258723,  0.84698444,
        1.87436648,  0.99999994,  0.98286395,  0.97620968,  0.95174829,
       -0.46492919,  0.86449823,  0.85232261,  0.67369264,  0.50194113,
       -0.7577829 ,  0.16477495,  0.03942791, -0.01887199, -0.02116257,
       -1.20429334, -0.57185507, -0.61055811, -0.76840349, -0.79218968,
       -1.46385562, -0.90249435, -0.91645396, -0.93297706, -0.93361619,
        0.35913976, -0.97242019, -0.97390003, -0.98669134, -0.99965138])

### *Training Model*

In [12]:
svr_rbf = SVR(kernel='rbf', C=1e4, gamma=0.1)
svr_lin = SVR(kernel='linear', C=1e4)
svr_poly = SVR(kernel='poly', C=1e4, degree=2)

In [13]:
y_rbf = svr_rbf.fit(X, y).predict(X)
y_lin = svr_lin.fit(X, y).predict(X)
y_poly = svr_poly.fit(X, y).predict(X)